# Generated by Django 3.1.4 on 2022-02-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220227_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('kind', models.IntegerField(choices=[(0, 'Not Known'), (3, 'Thriller'), (2, 'Comedy'), (1, 'Drama'), (4, 'Horror')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='kind',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.extrainfo'),
        ),
    ]
